# Generated by Django 3.2.16 on 2025-02-03
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_tiles(apps, schema_editor):
    """Создает начальные данные для клеток."""
    Tile = apps.get_model('monopoly', 'Tile')
    tiles_data = [
        {"name": "Старт", "type": "start", "position": 0},
        {"name": "Улица 1", "type": "property", "position": 1},
        {"name": "Улица 2", "type": "property", "position": 2},
        {"name": "Улица 3", "type": "property", "position": 3},
        {"name": "Улица 4", "type": "property", "position": 4},
        {"name": "Казна", "type": "treasury", "position": 5},
        {"name": "Улица 5", "type": "property", "position": 6},
        {"name": "Улица 6", "type": "property", "position": 7},
        {"name": "Улица 7", "type": "property", "position": 8},
        {"name": "Улица 8", "type": "property", "position": 9},
        {"name": "Тюрьма", "type": "jail", "position": 10},
        {"name": "Улица 9", "type": "property", "position": 11},
        {"name": "Улица 10", "type": "property", "position": 12},
        {"name": "Улица 11", "type": "property", "position": 13},
        {"name": "Улица 12", "type": "property", "position": 14},
        {"name": "Бесплатная парковка", "type": "free_parking", "position": 15},
        {"name": "Улица 13", "type": "property", "position": 16},
        {"name": "Улица 14", "type": "property", "position": 17},
        {"name": "Улица 15", "type": "property", "position": 18},
        {"name": "Улица 16", "type": "property", "position": 19},
    ]

    for tile_data in tiles_data:
        Tile.objects.create(**tile_data)

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('start', 'Старт'), ('jail', 'Тюрьма'), ('treasury', 'Казна'), ('free_parking', 'Бесплатная парковка'), ('property', 'Недвижимость')], max_length=50)),
                ('position', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=1500)),
                ('position', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='monopoly.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_of', to='monopoly.player'),
        ),
        migrations.RunPython(create_tiles),  # Вызываем функцию для создания клеток
    ]